### ISSUE TITLE
Update models with Featured field

### ISSUE THREAD

**Issue by esentis** [esentis/ieemdb-adopse-2021#28]
## Feature Request

Τα model του Movie, Artist, Director, Writer πρέπει να ενημερωθούν και να πάρουν ένα καινούργιο πεδίο "featured" που θα παίρνει default τιμή το **false**. 

Αυτό θα μας βοηθήσει να φτιάξουμε το featured screen οπου θα εχει στοιχεια που έχουν true το flag αυτό. Το flag θα αλλάζει απο τον ADMIN στον διαχειριστικό της ιστοσελίδας το οποίο θα έχει πρόσβαση ο διαχειριστής όταν εισέλθει στο σύστημα μας.

**Comment by vagmark30** [comment]
Αν εχω 1 εκατ εγγραφες θα πρεπει να διαβαζω και να συγκρινω το flag  απο 1 εκατ? Σαν λογικη μου φαινεται καλυτερο να υπαρχει ενα καινουργιο table Featured που θα εχει τα MovieId.

**Comment by esentis** [comment]
> Αν εχω 1 εκατ εγγραφες θα πρεπει να διαβαζω και να συγκρινω το flag απο 1 εκατ? Σαν λογικη μου φαινεται καλυτερο να υπαρχει ενα καινουργιο table Featured που θα εχει τα MovieId.

Εσυ δε παίρνεις τιποτα, το evaluation γίνεται στη βάση.
Το παρακάτω θα φέρει μόνο ότι ισχύει στο Where
```csharp
await Context.Movies.Where(movie=>movie.featured).ToListAsync();
```

Σε σύγκριση φυσικά με το :
```csharp
await Context.Movies.ToListAsync().Where(movie=>movie.featured).ToList();
```
το οποίο θα φέρει όλες τις ταινίες απο τη βάση και μετα θα τις φιλτράρει.
